import { ed25519 } from "@noble/curves/ed25519";
import { describe, expect, it } from "vitest";
import {
  decodeShortVec,
  isFullySigned,
  parseSolanaTransaction,
  signSolanaTransaction,
} from "./transaction";

/**
 * Every fixture here came out of `@solana/web3.js` v2 rather than out of
 * memory. Writing the expected bytes by hand would only prove this file agrees
 * with itself.
 *
 * Built from a fee payer whose seed is 32 bytes of 0x07, one System Program
 * instruction, and the all-zero blockhash.
 */
const SEED = new Uint8Array(32).fill(7);
const PUBKEY = ed25519.getPublicKey(SEED);

const hex = (s: string) =>
  new Uint8Array(s.match(/../g)!.map((b) => parseInt(b, 16)));

// Generated by @solana/web3.js v2, not transcribed. An earlier version of this
// file had these typed out by hand and was wrong by 32 bytes — the recent
// blockhash, which sits after the account keys and is all zeros here.
const V0_UNSIGNED = hex(
  "01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008001000102ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001010100040102030400",
);
const V0_SIGNED = hex(
  "014ac5c35ac3b67f019bff971d13731c10af1912b72ed975605797640c609aabdaa4a7a2b1aaf986ed86835457b7bdc571580ed42915d75b769320a8725a3409088001000102ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001010100040102030400",
);
const LEGACY_UNSIGNED = hex(
  "010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000102ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010101000401020304",
);
const LEGACY_SIGNED = hex(
  "019a1161660caa269678ce7c9de512dafc8d92e3f19b98e998a081940dd9a5296e7dd6af90a0d9f5cf8febd8f9a5ae808ac4c0de94df6645c0ec727cd94f55490501000102ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010101000401020304",
);

describe("decodeShortVec", () => {
  it("reads a one-byte length", () => {
    expect(decodeShortVec(hex("0500"), 0)).toEqual({ value: 5, size: 1 });
  });

  it("reads a continued length", () => {
    // 0x80 0x01 => 128
    expect(decodeShortVec(hex("800100"), 0)).toEqual({ value: 128, size: 2 });
  });

  it("refuses a prefix that never terminates", () => {
    expect(() => decodeShortVec(hex("808080"), 0)).toThrow("three bytes");
  });

  it("refuses to read past the end", () => {
    expect(() => decodeShortVec(hex("80"), 0)).toThrow("truncated");
  });
});

describe("parseSolanaTransaction", () => {
  it("locates the message of a versioned transaction", () => {
    const layout = parseSolanaTransaction(V0_UNSIGNED);
    expect(layout.version).toBe(0);
    expect(layout.signatureCount).toBe(1);
    expect(layout.numRequiredSignatures).toBe(1);
    expect(layout.messageOffset).toBe(65);
    // Exactly what @solana/web3.js reported as messageBytes.
    expect(layout.message[0]).toBe(0x80);
  });

  it("locates the message of a legacy transaction", () => {
    const layout = parseSolanaTransaction(LEGACY_UNSIGNED);
    expect(layout.version).toBe("legacy");
    expect(layout.numRequiredSignatures).toBe(1);
    // No version prefix: the header begins immediately.
    expect(layout.message[0]).toBe(1);
  });

  it("reads the signer key out of the account array", () => {
    const layout = parseSolanaTransaction(V0_UNSIGNED);
    expect(Array.from(layout.signerKeys[0])).toEqual(Array.from(PUBKEY));
  });

  it("refuses a transaction with fewer slots than signers", () => {
    // Claim zero signatures but a header requiring one.
    const bad = hex("00" + "01000102" + "00".repeat(64));
    expect(() => parseSolanaTransaction(bad)).toThrow("signature slots");
  });

  it("refuses a truncated account key array", () => {
    const bad = hex("01" + "00".repeat(64) + "010001" + "02" + "aa".repeat(40));
    expect(() => parseSolanaTransaction(bad)).toThrow("past the end");
  });

  it("refuses empty input", () => {
    expect(() => parseSolanaTransaction(new Uint8Array())).toThrow(
      "serialized Solana transaction is required",
    );
  });
});

describe("signSolanaTransaction", () => {
  // The whole point: byte-for-byte agreement with what the reference
  // implementation produces for the same key and the same message.
  it("produces the signature @solana/web3.js produces", () => {
    const signed = signSolanaTransaction(V0_UNSIGNED, SEED, PUBKEY);
    expect(Array.from(signed)).toEqual(Array.from(V0_SIGNED));
  });

  it("produces the same bytes for a legacy transaction", () => {
    const signed = signSolanaTransaction(LEGACY_UNSIGNED, SEED, PUBKEY);
    expect(Array.from(signed)).toEqual(Array.from(LEGACY_SIGNED));
    const layout = parseSolanaTransaction(signed);
    expect(ed25519.verify(signed.subarray(1, 65), layout.message, PUBKEY)).toBe(
      true,
    );
  });

  it("does not mutate the transaction it was given", () => {
    const before = Array.from(V0_UNSIGNED);
    signSolanaTransaction(V0_UNSIGNED, SEED, PUBKEY);
    expect(Array.from(V0_UNSIGNED)).toEqual(before);
  });

  // Signing anyway and placing the result nowhere in particular returns
  // something that looks signed and fails on submission.
  it("refuses a transaction this key does not sign", () => {
    const otherSeed = new Uint8Array(32).fill(9);
    const otherPub = ed25519.getPublicKey(otherSeed);
    expect(() =>
      signSolanaTransaction(V0_UNSIGNED, otherSeed, otherPub),
    ).toThrow("not a required signer");
  });

  it("leaves a co-signer's signature intact", () => {
    // Two slots, two signers: ours second.
    const other = new Uint8Array(64).fill(0xbb);
    const otherPub = new Uint8Array(32).fill(0xcc);
    const message = new Uint8Array([
      0x80, 2, 0, 1, 2, ...otherPub, ...PUBKEY,
    ]);
    const wire = new Uint8Array([
      2,
      ...other,
      ...new Uint8Array(64),
      ...message,
    ]);
    const signed = signSolanaTransaction(wire, SEED, PUBKEY);
    expect(Array.from(signed.subarray(1, 65))).toEqual(Array.from(other));
    expect(
      ed25519.verify(signed.subarray(65, 129), message, PUBKEY),
    ).toBe(true);
  });
});

describe("isFullySigned", () => {
  it("is false while a slot is still zero", () => {
    expect(isFullySigned(V0_UNSIGNED)).toBe(false);
  });

  it("is true once every required slot is filled", () => {
    expect(isFullySigned(V0_SIGNED)).toBe(true);
  });

  it("is false when a co-signer has not signed", () => {
    const otherPub = new Uint8Array(32).fill(0xcc);
    const message = new Uint8Array([0x80, 2, 0, 1, 2, ...PUBKEY, ...otherPub]);
    const wire = new Uint8Array([
      2,
      ...new Uint8Array(64).fill(1),
      ...new Uint8Array(64),
      ...message,
    ]);
    expect(isFullySigned(wire)).toBe(false);
  });
});
